<a href="https://colab.research.google.com/github/Vlvlan/Poznaj-Pythona-i-naucz-si-my-le-danymi-Kurs/blob/main/NumpyK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
tab = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
print(tab)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
tab = np.append(tab, [11,12,13,14,15.0, "hello"])

In [ ]:
print(tab)

['1.0' '2.0' '3.0' '4.0' '5.0' '6.0' '7.0' '8.0' '9.0' '10.0' '11.0'
 '12.0' '13.0' '14.0' '15.0' '11.0' '12.0' '13.0' '14.0' '15.0' '11' '12'
 '13' '14' '15.0' 'hello']


In [ ]:
print(tab.dtype)

float64


In [ ]:
tab = np.append(tab, [11,12,13,14,15.0, 20])

In [ ]:
print(tab)

['1.0' '2.0' '3.0' '4.0' '5.0' '6.0' '7.0' '8.0' '9.0' '10.0' '11.0'
 '12.0' '13.0' '14.0' '15.0' '11.0' '12.0' '13.0' '14.0' '15.0' '11' '12'
 '13' '14' '15.0' 'hello' '11.0' '12.0' '13.0' '14.0' '15.0' '20.0']


In [ ]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [ ]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [ ]:
print(np.full(5, 10))

[10 10 10 10 10]


In [ ]:
print(np.empty(5))

[5.e-323 5.e-323 5.e-323 5.e-323 5.e-323]


In [ ]:
print(np.arange(0, 15, 3))

[ 0  3  6  9 12]


In [ ]:
print(np.linspace(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
tablica_2d = np.array([[1,2,3], [4,5,6]])
print(tablica_2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(tablica_2d.ndim)

2


In [ ]:
print(tab.ndim)

1


In [ ]:
print(tablica_2d.shape)

(2, 3)


In [ ]:
print(tablica_2d.size)

6


In [ ]:
print(tab.size)

10


In [ ]:
tab_2 = tab.reshape(2,5)
print(tab_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
print(tab_2.ndim)

2


In [ ]:
print(tab[0:])

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(tab_2[0][4])

5


In [ ]:
print(tab_2[0:1, 0:3])

[[1 2 3]]


In [ ]:
x = np.array([0,5,10,15,20,25,30])

In [ ]:
print(x > 10)

[False False False  True  True  True  True]


In [ ]:
print(x[x > 10])

[15 20 25 30]


In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([10,15,20,25,30])


In [ ]:
print(a + b)

[11 17 23 29 35]


In [ ]:
t = 5

In [ ]:
print(a + t)

[ 6  7  8  9 10]


In [ ]:
a_2d = np.array([[1,2,3,4], [5,6,7,8]])
print(a_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b_2 = np.array([2,4,6,8])

In [ ]:
print(a_2d + b_2)

[[ 3  6  9 12]
 [ 7 10 13 16]]


In [ ]:
print(a - b)

[ -9 -13 -17 -21 -25]


In [ ]:
print(a / b)

[0.1        0.13333333 0.15       0.16       0.16666667]


In [ ]:
print(a * b)

[ 10  30  60 100 150]


In [ ]:
print(a * 2)

[ 2  4  6  8 10]


In [ ]:
print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
print(np.sin(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [ ]:
print(a.sum())

15


In [ ]:
print(a.mean())

3.0


In [ ]:
print(a.min())

1


In [ ]:
print(a.max())

5


In [ ]:
print(a_2d.sum(axis=1))

[10 26]


In [ ]:
x_3d = np.array([

      [[1,2,3,4],
       [5,6,7,8],
       [9,10,11,12]],

      [[13,14,15,16],
       [17,18,19,20],
       [21,22,23,24]]

])

In [ ]:
print(x_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
print(x_3d.ndim)

3


In [ ]:
print(x_3d.shape)

(2, 3, 4)


In [ ]:
print(x_3d[0][1][2])

7


In [ ]:
x_4d = np.arange(120).reshape(2, 3, 4, 5)

In [ ]:
print(x_4d)

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]


In [ ]:
produkty_AGD = [ ("Laptop", 6000), ("Myszka", 200), ("Klawiatura", 450), ("Monitor", 1200), ("Pendrive", 50), ("Słuchawki", 750), ("Podkładka", 40) ]

In [ ]:
one = list(filter(lambda x: x[1] > 100, produkty_AGD))
print(one)

[('Laptop', 6000), ('Myszka', 200), ('Klawiatura', 450), ('Monitor', 1200), ('Słuchawki', 750)]


In [ ]:
two = list(map(lambda x:( x[0], x[1] * 1.23), one))
print(two)

[('Laptop', 7380.0), ('Myszka', 246.0), ('Klawiatura', 553.5), ('Monitor', 1476.0), ('Słuchawki', 922.5)]


In [ ]:
three = sorted(two, key=lambda x: x[1])
print(three)

[('Myszka', 246.0), ('Klawiatura', 553.5), ('Słuchawki', 922.5), ('Monitor', 1476.0), ('Laptop', 7380.0)]
